num_jugadores = 0
num_jugadores_max = 4
#num_bots = 3
#num_jugador_real = 1
num_cartas_por_jugador = 2
num_cartas_presentes_en_mesa = 0 # inicialmente no hay cartas en la mesa
num_cartas_max_en_mesa = 5 
num_cartas_en_baraja = 52
num_cartas_restantes = num_cartas_en_baraja - (num_jugadores * num_cartas_por_jugador + num_cartas_presentes_en_mesa)